//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tSpeciality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSpeciality()
        {
            this.tblDoctors = new HashSet<Doctor>();
        }
    
        public int SpecId { get; set; }
        public string Speciality { get; set; }
       

        public Nullable<bool> IsSelected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> tblDoctors { get; set; }
    }
}
